---
# Creating or provisioning EC2 instance
- name: Create AWS resources for EC2 Instances
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    aws_region: us-east-1
    vpc_id: vpc-4cddce2a
    aws_access_key: ################# 
    aws_secret_key: #################
    my_local_cidr_ip: 0.0.0.0/0
    instance_type: t2.small
    ami_id: ami-b427a1ce
    key_name: yogeshaws
  tasks:
  - name: Create a security group
    ec2_group:
      name: ansible
      description: "Ansible Security Group"
      region: "{{aws_region}}"
      vpc_id: "{{vpc_id}}"
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
      rules:
        - proto: all
          cidr_ip: "{{my_local_cidr_ip}}"
        - proto: all
          group_name: ansible
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
    register: firewall
  - name: Create an EC2 instance
    ec2:
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
      key_name: "{{key_name}}"
      region: "{{aws_region}}"
      group_id: "{{firewall.group_id}}"
      instance_type: "{{instance_type}}"
      image: "{{ami_id}}"
      wait: yes
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 100
          delete_on_termination: true
      exact_count: 2
      count_tag:
         Name: aws-demo
      instance_tags:
         Name: aws-demo
    register: ec2

